/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center border-b text-black bg-white ">
          <h1 className="mx-10"><img src="/imagens/logo.png" alt="Logo Lacrei saude" /></h1>
          <nav className="flex gap-4 justify-end mx-10 ">
            <a className="p-2 rounded-md bg-foreground text-background hover:bg-background hover:text-foreground" href="http://localhost:3000/">Home</a>
            <a className="p-2 rounded-md bg-foreground text-background hover:bg-background hover:text-foreground" href="/about">About</a>
            <a className="p-2 rounded-md bg-foreground text-background hover:bg-background hover:text-foreground" href="/contact">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
